apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
nodeRegistration: {}
discovery:
  bootstrapToken:
    apiServerEndpoint: ${K8S_API_ENDPOINT_INTERNAL}
    token: ${KUBEADM_TOKEN}
    caCertHashes:
    - ${CA_CERT_HASH}